"""
Appendix A
Python-Based LLM Assistant for MITRE-Aware KQL Generation

This script implements a Python-based assistant that integrates structured
threat intelligence from OpenCTI with a Large Language Model (LLM) in order
to automatically generate Kusto Query Language (KQL) detection rules for
Microsoft Defender for Endpoint (MDE).

The assistant retrieves MITRE ATT&CK technique metadata via the OpenCTI
GraphQL API, constructs constrained prompts for the LLM, post-processes
the generated KQL to ensure schema compatibility, and supports iterative
human-in-the-loop refinement.
"""

import os
import json
import requests
from typing import Dict, List, Optional, Tuple
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI

# ──────────────────────────────────────────────────────────────
# Environment Setup and Configuration
# ──────────────────────────────────────────────────────────────

# Load environment variables from .env file
load_dotenv()

# Required credentials and endpoints
OPENAI_KEY = os.getenv("OPENAI_API_KEY")
OPENCTI_KEY = os.getenv("OPENCTI_API_KEY")
OPENCTI_URL = os.getenv("OPENCTI_URL", "").rstrip("/")

# Ensure all required configuration values are present
if not (OPENAI_KEY and OPENCTI_KEY and OPENCTI_URL):
    raise SystemExit(
        "Missing one or more required environment variables: "
        "OPENAI_API_KEY, OPENCTI_API_KEY, OPENCTI_URL"
    )

# Initialize the LLM client
# Temperature is set to 0 to ensure deterministic output
llm = ChatOpenAI(
    api_key=OPENAI_KEY,
    model="gpt-5-mini",
    temperature=0
)

# HTTP headers for authenticated communication with OpenCTI
HEADERS = {
    "Authorization": f"Bearer {OPENCTI_KEY}",
    "Content-Type": "application/json",
}

# ──────────────────────────────────────────────────────────────
# KQL Post-Processing and Normalization
# ──────────────────────────────────────────────────────────────

"""
LLM-generated KQL queries may contain invalid or inconsistent field names
due to differences between public documentation and the proprietary MDE
schema. The following mappings and helpers normalize common mistakes and
ensure mandatory fields are present.
"""

TABLE_FIELDS: Dict[str, Dict[str, str]] = {
    "DeviceProcessEvents": {
        "CommandLine": "ProcessCommandLine",
        "Commandline": "ProcessCommandLine",
        "InitiatingCommandLine": "InitiatingProcessCommandLine",
    },
    "DeviceNetworkEvents": {
        "CommandLine": "InitiatingProcessCommandLine",
        "Commandline": "InitiatingProcessCommandLine",
    },
    "DeviceFileEvents": {
        "CommandLine": "InitiatingProcessCommandLine",
        "Commandline": "InitiatingProcessCommandLine",
    },
}

# Mandatory fields required by MDE custom detections
MANDATORY_FIELDS = ["DeviceId", "ReportId"]


def clean_kql_output(kql: str) -> str:
    """
    Normalize and sanitize an LLM-generated KQL query.

    This function:
    - Detects the MDE table used in the query
    - Replaces commonly misused field names with valid schema fields
    - Ensures mandatory projection fields (DeviceId, ReportId) are included

    Parameters:
        kql (str): Raw KQL output generated by the LLM

    Returns:
        str: Cleaned and schema-compliant KQL query
    """
    if not kql:
        return kql

    lines = kql.splitlines()
    table_detected: Optional[str] = None

    # Identify which MDE table is being used
    for line in lines:
        stripped = line.strip()
        for table in TABLE_FIELDS.keys():
            if stripped.startswith(table):
                table_detected = table
                break
        if table_detected:
            break

    # Replace incorrect field names with correct schema fields
    if table_detected:
        for wrong, correct in TABLE_FIELDS[table_detected].items():
            kql = kql.replace(wrong, correct)

    # Ensure mandatory fields are projected
    lines = kql.splitlines()
    for i, line in enumerate(lines):
        if "| project" in line:
            try:
                right = line.split("| project", 1)[1]
                fields = [f.strip() for f in right.split(",") if f.strip()]
            except Exception:
                fields = []

            for f in MANDATORY_FIELDS:
                if f not in fields:
                    fields.append(f)

            lines[i] = "| project " + ", ".join(fields)
            kql = "\n".join(lines)
            break

    return kql

# ──────────────────────────────────────────────────────────────
# OpenCTI GraphQL Query Helpers
# ──────────────────────────────────────────────────────────────

def run_graphql_query(query: str, variables: Optional[dict] = None) -> dict:
    """
    Execute a GraphQL query against the OpenCTI API.

    Parameters:
        query (str): GraphQL query string
        variables (dict, optional): Query variables

    Returns:
        dict: Parsed JSON response from OpenCTI
    """
    payload = {"query": query}
    if variables:
        payload["variables"] = variables

    resp = requests.post(
        f"{OPENCTI_URL}/graphql",
        json=payload,
        headers=HEADERS,
        timeout=60
    )
    resp.raise_for_status()
    out = resp.json()

    if "errors" in out:
        raise RuntimeError(out["errors"])

    return out


def _pick_mitre_external_id(
    external_references: dict,
    fallback: Optional[str] = None
) -> Optional[str]:
    """
    Extract the MITRE ATT&CK external technique ID (e.g., T1003)
    from OpenCTI external references.
    """
    try:
        for edge in external_references.get("edges", []):
            node = edge.get("node", {})
            src = (node.get("source_name") or "").lower()
            if ("mitre" in src or "attack" in src) and node.get("external_id"):
                return node.get("external_id")
    except Exception:
        pass

    return fallback


def find_attack_pattern_by_external_id_or_name(term: str) -> Optional[dict]:
    """
    Search OpenCTI for a MITRE ATT&CK technique using either
    its external ID (e.g., T1558.003) or a name substring.

    Parameters:
        term (str): Technique name or ID

    Returns:
        dict or None: OpenCTI attack pattern object
    """
    safe_term = term.replace("\\", "\\\\").replace('"', '\\"')

    q_name = f"""
    query FindTechniqueByName {{
      attackPatterns(
        filters: {{
          mode: and,
          filters: [{{ key: "name", values: ["{safe_term}"] }}],
          filterGroups: []
        }},
        search: "{safe_term}"
      ) {{
        edges {{
          node {{
            id
            name
            description
            x_mitre_platforms
            isSubAttackPattern
            killChainPhases {{ phase_name kill_chain_name }}
            externalReferences {{
              edges {{ node {{ source_name external_id url }} }}
            }}
          }}
        }}
      }}
    }}
    """
    data = run_graphql_query(q_name)
    edges = data.get("data", {}).get("attackPatterns", {}).get("edges", [])

    if edges:
        node = edges[0]["node"]
        node["_resolved_external_id"] = _pick_mitre_external_id(
            node.get("externalReferences", {})
        )
        return node

    return None


def extract_mitre_context(ap: dict) -> Tuple[str, str, str, List[str], str]:
    """
    Extract relevant MITRE ATT&CK metadata from an OpenCTI attack pattern.

    Returns:
        Tuple containing:
        - Technique ID
        - Technique name
        - ATT&CK tactic
        - Target platforms
        - Shortened description
    """
    tech_id = ap.get("_resolved_external_id") or ap.get("external_id") or ""
    name = ap.get("name", "Unknown Technique")

    tactic = ""
    for kp in ap.get("killChainPhases", []):
        if kp.get("kill_chain_name") and "mitre" in kp["kill_chain_name"].lower():
            tactic = kp.get("phase_name") or ""
            break

    platforms = ap.get("x_mitre_platforms", []) or []
    desc = (ap.get("description") or "").strip()

    # Limit description length to keep prompts concise
    if len(desc) > 900:
        desc = desc[:900] + "…"

    return tech_id, name, tactic, platforms, desc

# ──────────────────────────────────────────────────────────────
# LLM Prompt Construction
# ──────────────────────────────────────────────────────────────

BASE_SYSTEM_BRIEF = (
    "You are a senior SOC analyst who writes precise Microsoft Defender for "
    "Endpoint (MDE) KQL. You always use the correct schema field names and "
    "produce queries that minimize false positives and false negatives. "
    "You include short inline comments (//) to show where an analyst can "
    "adapt filters. Output KQL only, no prose."
)

def build_prompt_for_technique(
    tech_id: str,
    name: str,
    tactic: str,
    platforms: List[str],
    description: str,
    env_hints: Optional[dict] = None
) -> str:
    """
    Construct a constrained prompt that embeds MITRE ATT&CK context
    and optional environment-specific tuning hints.
    """
    env_hints = env_hints or {}
    tuning_text = []

    if env_hints.get("exclude_accounts"):
        tuning_text.append(f"Exclude accounts: {', '.join(env_hints['exclude_accounts'])}")
    if env_hints.get("exclude_devices"):
        tuning_text.append(f"Exclude devices: {', '.join(env_hints['exclude_devices'])}")
    if env_hints.get("exclude_processes"):
        tuning_text.append(f"Exclude processes: {', '.join(env_hints['exclude_processes'])}")
    if env_hints.get("business_hours"):
        tuning_text.append(f"Business hours: {env_hints['business_hours']}")
    if env_hints.get("device_groups"):
        tuning_text.append(f"Device groups of interest: {', '.join(env_hints['device_groups'])}")

    tuning = "\n".join(f"- {t}" for t in tuning_text) if tuning_text else "- (No explicit environment hints)"

    prompt = f"""
Generate an MDE KQL query to detect the MITRE ATT&CK technique below.
Use correct MDE schema and reduce false positives.

Technique ID: {tech_id}
Technique Name: {name}
ATT&CK Tactic: {tactic}
Platforms: {', '.join(platforms) if platforms else 'n/a'}
Technique Summary: {description}

Environment hints for tuning:
{tuning}

Constraints:
- Prefer tables: DeviceProcessEvents, DeviceNetworkEvents,
  DeviceLogonEvents, IdentityLogonEvents
- Always include DeviceId and ReportId in the final projection
- Add filters to avoid normal administrative activity
- If multiple queries are needed, union them
- Output KQL only
"""
    return prompt.strip()


def generate_kql_from_prompt(prompt: str) -> str:
    """
    Send the constructed prompt to the LLM and post-process the output.
    """
    raw = llm.invoke([
        {"role": "system", "content": BASE_SYSTEM_BRIEF},
        {"role": "user", "content": prompt},
    ]).content

    return clean_kql_output(raw.strip())

# ──────────────────────────────────────────────────────────────
# Interactive CLI and Refinement Loop
# ──────────────────────────────────────────────────────────────

_LAST_TECH_CONTEXT: Optional[dict] = None

def interactive_refinement_loop(initial_kql: str) -> str:
    """
    Allow a human analyst to iteratively refine the generated KQL
    by providing environment-specific constraints.
    """
    kql = initial_kql

    while True:
        print("\n——— KQL ———\n")
        print(kql)
        print("\n——————————\n")

        choice = input("Refine? (y = refine / n = accept / e = exit): ").lower()
        if choice == "n":
            return kql
        if choice == "e":
            raise SystemExit(0)

        if choice == "y" and _LAST_TECH_CONTEXT:
            hints = {}
            ex_acc = input("Exclude accounts (comma-separated): ").strip()
            if ex_acc:
                hints["exclude_accounts"] = [a.strip() for a in ex_acc.split(",")]

            prompt = build_prompt_for_technique(
                _LAST_TECH_CONTEXT["tech_id"],
                _LAST_TECH_CONTEXT["name"],
                _LAST_TECH_CONTEXT["tactic"],
                _LAST_TECH_CONTEXT["platforms"],
                _LAST_TECH_CONTEXT["description"],
                env_hints=hints,
            )
            kql = generate_kql_from_prompt(prompt)

# ──────────────────────────────────────────────────────────────
# Main Program Flow
# ──────────────────────────────────────────────────────────────

def main():
    """
    Entry point for the assistant.
    """
    global _LAST_TECH_CONTEXT

    while True:
        term = input("Enter MITRE technique name or ID (or 'exit'): ").strip()
        if term.lower() == "exit":
            break

        ap = find_attack_pattern_by_external_id_or_name(term)
        if not ap:
            print("Technique not found in OpenCTI dataset.")
            continue

        tech_id, name, tactic, platforms, desc = extract_mitre_context(ap)
        _LAST_TECH_CONTEXT = {
            "tech_id": tech_id,
            "name": name,
            "tactic": tactic,
            "platforms": platforms,
            "description": desc,
        }

        prompt = build_prompt_for_technique(tech_id, name, tactic, platforms, desc)
        kql = generate_kql_from_prompt(prompt)
        final_kql = interactive_refinement_loop(kql)

        print("\nFinal KQL:\n")
        print(final_kql)
        print("\n" + "=" * 60 + "\n")

if __name__ == "__main__":
    main()
